sudo: required
language: go
go:
  - 1.9
  # - 1.10
  - tip
matrix:
  allow_failures:
    - go: tip

before_install:
  - go get github.com/haya14busa/goverage github.com/mattn/goveralls github.com/stretchr/testify/assert
  - go get -v ./...
before_script:
  - go vet ./... 2>&1 | grep -v "\(in Errorf call\|exit status 1\)" > vet.log ; test ! -s vet.log
  - gofmt -s -l .
script:
  - goverage -v -coverprofile="coverage.out" ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
