name: test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: setup env
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}"
        echo "::add-path::${{ github.workspace }}/bin"
      shell: bash

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: src/github.com/evalphobia/hierogolyph

    - name: Test
      run: |
        make init
        make test
      working-directory: src/github.com/evalphobia/hierogolyph

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make send-coverage
      working-directory: src/github.com/evalphobia/hierogolyph
